engines:
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.js"
    - "**.md"
exclude_paths:
  - "node_modules/**/*"
  - "docs/**/*"
